- hooks:
  - id: trailing-whitespace
  - exclude: VERSION$
    id: end-of-file-fixer
  - files: ^.pre-commit-config.yaml$
    id: check-yaml
    name: Check pre-commit config
  repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
- hooks:
  - id: nixpkgs-fmt
    name: Format .nix files
  repo: git://github.com/nix-community/nixpkgs-fmt
  rev: v1.0.0
- hooks:
  - args: ["--format=tty", "--shell=bash"]
    files: ^.envrc$
    id: shell-lint
    name: Lint .envrc
    types: [text]
  repo: git://github.com/detailyang/pre-commit-shell
  rev: v1.0.6
- hooks:
  - description: Prettify Haskell code with ormolu
    entry: "ormolu --mode inplace"
    files: '.+\.hs$'
    id: ormolu
    language: system
    name: Prettify Haskell code
  repo: local
